---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - ajcarberry.packer-debian

  tasks:
    - apt:
        pkg:
          - git
          - wget
          - curl
          - vim
          - dkms
          - dstat
          - dbus
          - iftop
          - tcpdump
          - screen
          - rsync
          - ntp
          - python-dev
          - python-pip
          - unzip
        state: present
